import type { Metadata } from "next";
import "./globals.css";
import Header from "@/app/components/Header";
import React from "react";
import Footer from "@/app/components/Footer";
import ThemeProvider from "@/app/components/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
            <body suppressHydrationWarning>
                <ThemeProvider>
                    <Header/>
                    <main>{children}</main>
                    <Footer/>
                </ThemeProvider>
            </body>
        </html>
    );
}

